version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./yavuzlar.db:/var/www/html/yavuzlar.db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped

  # İsteğe bağlı: PHPMyAdmin (eğer MySQL'e geçmek isterseniz)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8081:80"
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306
  #   depends_on:
  #     - db